apiVersion: v1
kind: Secret
metadata:
  name: er-frappe-aks-share-secret
  namespace: frappe-base
type: Opaque
data:
  azurestorageaccountname: ZXJiazhzYXBwYWxs
  azurestorageaccountkey: V0FFOEdabWttZFRtWXE0cUF5TGd4azk1OGF4c1FzYUlSYlNQQWlJNk53L3IrbGZGbU40TG45ZERKZDhnQlZJalp3WWlCMFJOZ1dRN2lKUTFlN25JWnc9PQ==
