kind: Endpoints
apiVersion: v1
metadata:
 name: {{ .Release.Name }}-db-ntex-com
 namespace: {{ .Values.targetNamespace }}
subsets:
 - addresses:
     - ip: {{ .Values.db.host }}
   ports:
     - port: {{ .Values.db.port | default 3306 }}
