apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: er-frappe-sites-pvc
  namespace: {{ .Values.targetNamespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacityInGi }}Gi
